!==============================================================================!
  subroutine File_Mod_Example
!------------------------------------------------------------------------------!
!   Subroutine to create an example file                                       !
!==============================================================================!

  call File_Mod_Logo

  open(FU, file = "example.d")

  write(FU, *)  "#*******************************************************"
  write(FU, *)  ""
  write(FU, *)  "  Everything enclosed inside the cashes is a comment."   
  write(FU, *)  ""
  write(FU, *)  "  This input file is used to generate the triangular"
  write(FU, *)  "  mesh over the following domain:"
  write(FU, *)  ""
  write(FU, *)  "     3--------------------2"
  write(FU, *)  "     |                    |"
  write(FU, *)  "     |    5----6          |"
  write(FU, *)  "     |    |    |          |"
  write(FU, *)  "     |    |    |          |"
  write(FU, *)  "     |    4----7          |"
  write(FU, *)  "     |                    |"
  write(FU, *)  "     0--------------------1"
  write(FU, *)  ""
  write(FU, *)  ""
  write(FU, *)  "  Run EasyMesh with the command:"
  write(FU, *)  ""
  write(FU, *)  "  > EasyMesh example +fig"
  write(FU, *)  " "
  write(FU, *)  "  if you want to see the results with xfig,"
  write(FU, *)  "  or with"
  write(FU, *)  ""
  write(FU, *)  "  > EasyMesh example +dxf"
  write(FU, *)  ""
  write(FU, *)  "  if you want to see the results with some tool that"
  write(FU, *)  "  suports Autodesk DXF format"
  write(FU, *)  ""
  write(FU, *)  "*******************************************************#"
  write(FU, *)  ""
  write(FU, *)  "#*********"
  write(FU, *)  "  POINTS"
  write(FU, *)  "*********#"
  write(FU, *)  "8 # number of points defining the boundary #"
  write(FU, *)  ""
  write(FU, *)  "# rectangular domain #"
  write(FU, *)  "#-------+-----+-----+---------+--------#"
  write(FU, *)  "# point |  x  |  y  | spacing | marker #"
  write(FU, *)  "#-------+-----+-----+---------+--------#"
  write(FU, *)  "   0:     0.0   0.0    0.05       1"
  write(FU, *)  "   1:     2.0   0.0    0.25       2"
  write(FU, *)  "   2:     2.0   1.6    0.25       2"
  write(FU, *)  "   3:     0.0   1.6    0.1        1"
  write(FU, *)  ""
  write(FU, *)  "# square hole #"
  write(FU, *)  "#-------+-----+-----+---------+--------#"
  write(FU, *)  "# point |  x  |  y  | spacing | marker #"
  write(FU, *)  "#-------+-----+-----+---------+--------#"
  write(FU, *)  "   4:     0.5   0.5    0.05       3"
  write(FU, *)  "   5:     0.5   1.1    0.08       3"
  write(FU, *)  "   6:     1.1   1.1    0.2        3"
  write(FU, *)  "   7:     1.1   0.5    0.2        3"
  write(FU, *)  ""
  write(FU, *)  "#***********"
  write(FU, *)  "  SEGMENTS"
  write(FU, *)  "***********#"
  write(FU, *)  "8 # number of segments #"
  write(FU, *)  ""
  write(FU, *)  "# domain #"
  write(FU, *)  "#---------+-----+-----+--------#"
  write(FU, *)  "# segment | 1st | 2nd | marker #"
  write(FU, *)  "#---------+-----+-----+--------#"
  write(FU, *)  "     0:      0     1      1"
  write(FU, *)  "     1:      1     2      2"
  write(FU, *)  "     2:      2     3      1"
  write(FU, *)  "     3:      3     0      1"
  write(FU, *)  ""
  write(FU, *)  "# hole #"
  write(FU, *)  "#---------+-----+-----+--------#"
  write(FU, *)  "# segment | 1st | 2nd | marker #"
  write(FU, *)  "#---------+-----+-----+--------#"
  write(FU, *)  "     4:      4     5      3"
  write(FU, *)  "     5:      5     6      3"
  write(FU, *)  "     6:      6     7      3"
  write(FU, *)  "     7:      7     4      3"

  close(FU)

  print *, "The file 'example.d' created !"
  print *, ""

  end subroutine
