!==============================================================================!
  subroutine File_Mod_Example
!------------------------------------------------------------------------------!
!   Subroutine to create an example file                                       !
!==============================================================================!

  call File_Mod_Logo

  open(FU, file = "example.d")
  write(FU, *)  "#*******************************************************"
  write(FU, *)  ""
  write(FU, *)  "  Everything enclosed inside the cashes is a comment."   
  write(FU, *)  ""
  write(FU, *)  "  This input file is used to generate the triangular"
  write(FU, *)  "  mesh over the following domain:"
  write(FU, *)  ""
  write(FU, *)  "     4--------------------3"
  write(FU, *)  "     |                    |"
  write(FU, *)  "     |    6----7          |"
  write(FU, *)  "     |    |    |          |"
  write(FU, *)  "     |    |    |          |"
  write(FU, *)  "     |    5----8          |"
  write(FU, *)  "     |                    |"
  write(FU, *)  "     1--------------------2"
  write(FU, *)  ""
  write(FU, *)  ""
  write(FU, *)  "  Run Tripos with the command:"
  write(FU, *)  ""
  write(FU, *)  "  > Tripos example +eps"
  write(FU, *)  " "
  write(FU, *)  "  if you want to see the results with ghostview,"
  write(FU, *)  "  or with"
  write(FU, *)  ""
  write(FU, *)  "  > Tripos example +dxf"
  write(FU, *)  ""
  write(FU, *)  "  if you want to see the results with some tool that"
  write(FU, *)  "  suports Autodesk DXF format"
  write(FU, *)  ""
  write(FU, *)  "*******************************************************#"
  write(FU, *)  ""
  write(FU, *)  "#*********"
  write(FU, *)  "  POINTS"
  write(FU, *)  "*********#"
  write(FU, *)  "8 # number of points defining the boundary #"
  write(FU, *)  ""
  write(FU, *)  "# rectangular domain #"
  write(FU, *)  "#-------+-----+-----+---------+--------#"
  write(FU, *)  "# point |  x  |  y  | spacing | marker #"
  write(FU, *)  "#-------+-----+-----+---------+--------#"
  write(FU, *)  "   1:     0.0   0.0    0.02       1"
  write(FU, *)  "   2:     2.4   0.0    0.12       1"
  write(FU, *)  "   3:     2.4   1.6    0.12       1"
  write(FU, *)  "   4:     0.0   1.6    0.04       1"
  write(FU, *)  ""
  write(FU, *)  "# square hole #"
  write(FU, *)  "#-------+-----+-----+---------+--------#"
  write(FU, *)  "# point |  x  |  y  | spacing | marker #"
  write(FU, *)  "#-------+-----+-----+---------+--------#"
  write(FU, *)  "   5:     0.5   0.5    0.03       3"
  write(FU, *)  "   6:     0.5   1.1    0.03       3"
  write(FU, *)  "   7:     1.1   1.1    0.04       3"
  write(FU, *)  "   8:     1.1   0.5    0.04       3"
  write(FU, *)  ""
  write(FU, *)  "#***********"
  write(FU, *)  "  SEGMENTS"
  write(FU, *)  "***********#"
  write(FU, *)  "8 # number of segments #"
  write(FU, *)  ""
  write(FU, *)  "# domain #"
  write(FU, *)  "#---------+-----+-----+--------#"
  write(FU, *)  "# segment | 1st | 2nd | marker #"
  write(FU, *)  "#---------+-----+-----+--------#"
  write(FU, *)  "     1:      1     2      1"
  write(FU, *)  "     2:      2     3      2"
  write(FU, *)  "     3:      3     4      1"
  write(FU, *)  "     4:      4     1      2"
  write(FU, *)  ""
  write(FU, *)  "# hole #"
  write(FU, *)  "#---------+-----+-----+--------#"
  write(FU, *)  "# segment | 1st | 2nd | marker #"
  write(FU, *)  "#---------+-----+-----+--------#"
  write(FU, *)  "     5:      5     6      3"
  write(FU, *)  "     6:      6     7      3"
  write(FU, *)  "     7:      7     8      3"
  write(FU, *)  "     8:      8     5      3"
  print *, "File 'example.d' created !"
  close(FU)

  open(FU, file = "example.b")
  write(FU, *)  "#*****************************************"
  write(FU, *)  ""
  write(FU, *)  "  A file to specify boundary conditions."
  write(FU, *)  ""
  write(FU, *)  "*****************************************#"
  write(FU, *)  ""
  write(FU, *)  "3 # number of boundary conditions #"
  write(FU, *)  ""
  write(FU, *)  "#------+------+----------#"
  write(FU, *)  "# b.c. | type | b. value #"
  write(FU, *)  "#------+------+----------#"
  write(FU, *)  "   1:     D      100.0"
  write(FU, *)  "   2:     N        0.0"
  write(FU, *)  "   3:     D      200.0"
  print *, "File 'example.b' created !"
  close(FU)

  open(FU, file = "example.m")
  write(FU, *)  "#********************************************************"
  write(FU, *)  ""
  write(FU, *)  "  A file to specify material properties and conditions."
  write(FU, *)  ""
  write(FU, *)  "********************************************************#"
  write(FU, *)  ""
  write(FU, *)  "1 # number of materials"
  write(FU, *)  ""
  write(FU, *)  "#----------+-----------------------+--------#"
  write(FU, *)  "# material | diffusion coefficient | source #"
  write(FU, *)  "#----------+-----------------------+--------#"
  write(FU, *)  "     1:              0.01             0.0"
  print *, "File 'example.m' created !"
  print *, ""
  close(FU)

  end subroutine
